---
layout: single
sidebar:
  nav: matlab_sidebar
title: "Matlab" 
toc: true
toc_sticky: true
---

Welcome to Matlab, an engineering focused coding language that makes data analysis easier

-------------------------------------------------------------------------------

## What is Matlab? 


Matlab is an online coding platform which allows you to analyze complex datasets. 


**Matlabs function capabilities** make it great for engineering as you can run 
complex cacluations using calculus based functions. 


**Visualizing** capabilites are also vast with matlab, as you are able to 
visualize 3d and 4d models with it. THere are also a wide array of aesthetic options 
to modify your graphs. 


## Why learn Matlab?


Matlab is especially beneficial if you are an engineer or engineering student as this 
is a widely used software in the discipline. 


Matlab also allows you to learn how to analyze and manipulate your data in complex ways 
that other coding softwares may not offer. 


## Resources 

